base_url = "https://tales.dev"
title = "Tales Cione | Software Developer"
description = "A software developer from São Paulo living in Berlin"
default_language = "en"
compile_sass = true
build_search_index = false
generate_feed = true
taxonomies = [
  { name = "tags", feed = true}
]

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
